#!/usr/bin/env bash
# Build a minimal InfraGod.app bundle and add it to macOS Login Items.
#
# Why an .app bundle?
# macOS 14+ enforces Local Network privacy on a per-app basis. LaunchAgent
# spawned processes can't reach LAN IPs. A proper .app with
# NSLocalNetworkUsageDescription gets a one-time user prompt, then full
# LAN access — and Login Items + LSUIElement give us silent auto-start.
#
# Usage: ./install.sh
# Re-run any time you rebuild the binary or change servers.yaml location.
# Credentials live in ~/.infra-god/.env (loaded by the binary itself).

set -euo pipefail

APP_NAME="InfraGod"
BUNDLE_ID="com.kangthink.infra-god"
APP_DIR="${HOME}/Applications/${APP_NAME}.app"
LOG_DIR="${HOME}/Library/Logs/infra-god"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find binary
BINARY="$(command -v infra-god 2>/dev/null || true)"
if [ -z "${BINARY}" ]; then
  for cand in /usr/local/bin/infra-god /opt/homebrew/bin/infra-god "${HOME}/go/bin/infra-god"; do
    [ -x "${cand}" ] && BINARY="${cand}" && break
  done
fi
if [ -z "${BINARY}" ]; then
  echo "❌ infra-god binary not found. Install it first:" >&2
  echo "   cd $(cd "${SCRIPT_DIR}/../.." && pwd) && go build -o /usr/local/bin/infra-god ." >&2
  exit 1
fi

# Resolve config
DEFAULT_WD="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKING_DIR="${INFRA_GOD_WORKDIR:-${DEFAULT_WD}}"
if [ -f "${WORKING_DIR}/servers.yaml" ]; then
  CONFIG="${WORKING_DIR}/servers.yaml"
elif [ -f "${HOME}/.infra-god/servers.yaml" ]; then
  CONFIG="${HOME}/.infra-god/servers.yaml"
else
  echo "❌ servers.yaml not found in ${WORKING_DIR} or ~/.infra-god/" >&2
  exit 1
fi

if [ ! -f "${HOME}/.infra-god/.env" ]; then
  echo "ℹ️  ~/.infra-god/.env not found. If servers.yaml uses password_env, create it:"
  echo "   echo 'INFRA_SSH_PASS=...' > ${HOME}/.infra-god/.env && chmod 600 ${HOME}/.infra-god/.env"
fi

# 1) Stop any running instance (so we don't double-bind 9998)
pkill -f 'infra-god serve' 2>/dev/null || true
osascript -e 'tell application "System Events" to delete login item "InfraGod"' 2>/dev/null || true

# 2) Build the .app bundle
mkdir -p "${APP_DIR}/Contents/MacOS"
mkdir -p "${LOG_DIR}"

# Info.plist
cat > "${APP_DIR}/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>infra-god webui</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>10.15</string>
    <key>NSLocalNetworkUsageDescription</key>
    <string>infra-god monitors your servers over SSH. It needs Local Network access to reach LAN IPs in servers.yaml.</string>
    <key>NSBonjourServices</key>
    <array>
        <string>_ssh._tcp</string>
    </array>
</dict>
</plist>
EOF

# Executable shell script
# Note: INFRA_SSH_PASS (and other env vars) loaded by the binary from
# ~/.infra-god/.env at startup. Don't bake them into the launcher script —
# baking an empty value would shadow the .env value (godotenv won't override
# an already-set var, even if empty).
cat > "${APP_DIR}/Contents/MacOS/${APP_NAME}" <<EOF
#!/bin/sh
# Generated by scripts/autostart/install.sh
export PATH='/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin'
cd '${WORKING_DIR}' || exit 1
exec '${BINARY}' serve --addr '0.0.0.0:9998' --config '${CONFIG}' \\
  >> '${LOG_DIR}/infra-god.out.log' 2>> '${LOG_DIR}/infra-god.err.log'
EOF
chmod +x "${APP_DIR}/Contents/MacOS/${APP_NAME}"

# 3) Codesign ad-hoc so TCC tracks it as a stable identity
codesign --force --deep --sign - "${APP_DIR}" 2>/dev/null || true

# 4) Add to Login Items (silently start at login)
osascript <<EOF
tell application "System Events"
  if not (login item "${APP_NAME}" exists) then
    make login item at end with properties {path:"${APP_DIR}", hidden:true}
  end if
end tell
EOF

# 5) Open it now to trigger Local Network prompt
open -gj "${APP_DIR}"
sleep 2

# 6) Verify
URL="http://localhost:9998/healthz"
ok=0
for i in 1 2 3 4 5; do
  if curl -sf "${URL}" >/dev/null 2>&1; then ok=1; break; fi
  sleep 2
done

IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "<lan-ip>")"

echo
if [ "${ok}" = "1" ]; then
  echo "✅ InfraGod.app is running."
else
  echo "⚠️  app installed but /healthz not responding yet."
fi
echo "   본인:        http://localhost:9998/"
echo "   사내 공유:   http://${IP}:9998/"
echo "   app:         ${APP_DIR}"
echo "   logs:        ${LOG_DIR}/infra-god.{out,err}.log"
echo
echo "🔔 처음 실행 시 macOS가 'Local Network 접근 허용' 알림을 띄울 수 있습니다."
echo "   '허용'을 누르면 LAN 서버에 접근 가능해집니다. 한 번만 답하면 영구 적용."
echo "   알림 놓쳤다면: 시스템 설정 → 개인정보 보호 → 로컬 네트워크 → InfraGod 켜기"
echo
echo "확인:  ${SCRIPT_DIR}/check.sh"
echo "제거:  ${SCRIPT_DIR}/uninstall.sh"
